import { ISellerProduct } from "./seller-products.interface";

export const sellerProductsTest: ISellerProduct[] = [
  {
    id: 1,
    image: "",
    status: "Не прошел модерацию",
    status_code: "rejected",
    slug: "test",
    specifications: {},
    name: "test",
    description: "test",
    price: "100",
    images: [],
  },
  {
    id: 5,
    image: "",
    status: "На модерации",
    status_code: "pending",
    slug: "test",
    specifications: {},
    name: "ngt kbgdnbon; dbnodk nbfdnbn odnfb ngt kbgdnbon; dbnodk nbfdnbn odnfb",
    description: "test",
    price: "100",
    images: [],
  },
  {
    id: 2,
    image: "",
    status: "В архиве",
    status_code: "archived",
    slug: "test",
    specifications: {},
    name: "test",
    description: "test",
    price: "100",
    images: [],
  },
  {
    id: 3,
    image: "",
    status: "Черновик",
    status_code: "draft",
    slug: "test",
    specifications: {},
    name: "test",
    description: "test",
    price: "100",
    images: [],
  },
  {
    id: 4,
    image: "",
    status: "Одобрен",
    status_code: "approved",
    slug: "test",
    specifications: {},
    name: "test",
    description: "test",
    price: "100",
    images: [],
  },
];
