import { IProfile } from "./user.interface";

export const profileChangeableFields: (keyof IProfile)[] = [
  "email",
  "name",
  "surname",
  "avatar",
  "company_name",
  "company_type",
  "shop_name",
  "inn",
  "kpp",
  "ogrn",
  "legal_address",
  "actual_address",
  "storage_city",
  "company_address",
  "bank_account",
  "bank_bik",
  "correspondent_account",
  "bank_name",
  "director_surname",
  "director_name",
  "accountant_is_director",
  "accountant_surname",
  "accountant_name",
  "accountant_patronymic",
  "agreement_accepted",
];
